### ISSUE TITLE
Abstract for RACI NSW Organic symposium

### ISSUE THREAD

**Issue by ErinSheridan** [TheBreakingGoodProject/Daraprim#1]
We (the Sydney Grammar group) are hoping to present a poster at the [NSW Organic Symposium](https://www.raci.org.au/events/event/nsw-organic-one-day-symposium-2017) on our progress towards the synthesis of Daraprim analogues.  We've written a draft abstract, but would love any helpful comments/proof-reading.

Thanks @alintheopen for your help so far!

[Analogues of Daraprim for the treatment of malaria and toxoplasmosis_2_AEW.docx](https://github.com/TheBreakingGoodProject/Daraprim/files/1477041/Analogues.of.Daraprim.for.the.treatment.of.malaria.and.toxoplasmosis_2_AEW.docx)
@AJIC @KieranCo @HThawley @buddycelyn @Ollie555h @hugomccb

**Comment by alintheopen** [comment]
Presented in December 2018! 
![sgs](https://user-images.githubusercontent.com/2626599/40092821-ad05a198-5902-11e8-96f9-a6e11df67944.png)
![sgs-2](https://user-images.githubusercontent.com/2626599/40092822-ad34f7e0-5902-11e8-98b5-8d2c8f4186ac.png)
